### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by mischapeters** [mkxml/atom-filesize#1]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.

```
Atom.Object.defineProperty.get (/Users/mischa/Applications/Atom.app/Contents/Resources/app/src/atom.js:54:11)
FilesizeView.hide (/Users/mischa/.atom/packages/filesize/lib/filesize-view.coffee:54:23)
```

**Comment by mkxml** [comment]
Thanks for the report @mischapeters. I'll will check out the new API and get a fix.

**Comment by mischapeters** [comment]
Sorry for the impersonal ticker. Just clicked on "Deprecation Cop" open issue.
Thanx for fixing this so fast!
