### ISSUE TITLE
use the current theme's coloring instead of the blue-based colors

### ISSUE THREAD

**Issue by varemenos** [mkxml/atom-filesize#11]
Currently the pop-up seems out of place because the rest of the editor is has different colors, could you please utilize the colors from the current theme to style the popup?

**Comment by mkxml** [comment]
That is a concern to the plugin. As you can see on the screenshots it tries to follow the current theme style.

Can you please inform your current UI and syntax themes?

**Comment by varemenos** [comment]
I see, based on the color choices of the theme I assumed the colors were hardcoded and since this is not the case this issue is invalid.
