### ISSUE TITLE
The popup window should auto disappear when mouse leaves.

### ISSUE THREAD

**Issue by ibtwbbab** [mkxml/atom-filesize#12]
Hi, as the title says, I believe it will make the window more convenient.

**Comment by mkxml** [comment]
I agree with that approach, as long as we make sure the user can still copy some text from the popup.

So to implement it we must detect if the user moved the mouse away from the status bar or the popup itself.

I can't take the issue right now (working on other projects), but I'm open to PRs.

Thank you for your feedback.

**Comment by julkue** [comment]
At least when clicking outside the window.

**Comment by mkxml** [comment]
Hello @ibtwbbab and @julmot.

The package has been completely rewritten and should be 100% compatible with Atom 1.0+.

Also, the tooltip now dismisses when clicking away from it. You may test it by upgrading the package to the latest version through Atom.
