### ISSUE TITLE
Changes required for upcoming CoffeeScript upgrade

### ISSUE THREAD

**Issue by maxbrunsfeld** [mkxml/atom-filesize#13]
Hi! Thanks for maintaining the filesize package!

In Atom v1.12, we are going to [upgrade CoffeeScript](https://github.com/atom/atom/pull/12780) to the latest version. This upgrade entails one potentially breaking change to the language:

> Changed strategy for the generation of internal compiler variable names. Note that this means that @example function parameters are no longer available as naked example variables within the function body.

We think your package may be affected by this upgrade, in the following places:
- The `multiple` variable [here](https://github.com/mkautzmann/atom-filesize/tree/master/lib/filesize-calculator.coffee#L51)

These findings are based on linting packages with `coffeescope`. We could be wrong about some of them. When we release v1.12 beta, please test your package against it to make sure that it works. Let me know if you have any further questions; I will be happy to help!

**Comment by mkxml** [comment]
Thank you for the heads up! I'll look into it.

**Comment by mkxml** [comment]
Hello @maxbrunsfeld.

The package is now written in plain JS/ES2015.

I've tested with the beta version of Atom, precisely the [1.12-beta0](https://github.com/atom/atom/releases/tag/v1.12.0-beta0) one and it seems to work just fine.

I'll keep testing with future versions to make sure things won't break.
