### ISSUE TITLE
The popup window is displayed deform

### ISSUE THREAD

**Issue by donatoaguirre24** [mkxml/atom-filesize#18]
![captura realizada el 2016-12-14 17 28 53](https://cloud.githubusercontent.com/assets/20030075/21199571/d3a84a94-c222-11e6-98ce-e9ad12da5e75.jpeg)

**Comment by mkxml** [comment]
Thanks for reporting this. Sorry for the delay.

Well, it looks like it has something to do with the theme you are using.

Can you tell me what is the name of this theme?

Can you test with the default One Dark theme just to be sure it is theme-related?

**Comment by donatoaguirre24** [comment]
I tested with one dark theme, atom dark  and works fine so you're right I'm pretty sure than it's theme-related. 

The theme with I have the issue is Atom Material so if you can fix it or tell me how do that I would be very grateful.

**Comment by mkxml** [comment]
Thanks for reporting this @donatoaguirre24! The fix is already available in version v2.0.4. Please update `atom-filesize` and make sure you're running the latest Atom version too.

Please let me know if you find any further troubles with the package.

Happy coding!
