### ISSUE TITLE
Bubble File Properties

### ISSUE THREAD

**Issue by felipekm** [mkxml/atom-filesize#2]
How about to include all file properties on a popup when hover the filesize info?

**Comment by mkxml** [comment]
OK, I thought about some ideas of possible extra data. It's important to notice that we have to be careful to not **overlap** features already available in Atom. What do you think of the following items:
- Absolute path
- Mime type
- Date of creation
- Date of last change

It's also important to know that currently the `filesize` package only access OS meta data about the file, it does not perform any extra look that would be needed to get SLOC or dimensions in media files. Doing such checks would increase load time considerably.

What do you think? Any ideas?

**Comment by felipekm** [comment]
Yeah right, that's basically my mindset on that.
- Absolute path
- Mime type
- Date of creation
- Date of last change
- Image Dimensions when available

Nothing about SLOC surely, but I was wondering about dimensions when it is an Image File, are you sure about performance issue on that?

**Comment by mkxml** [comment]
I think it can be done. I will take a look on this soon.

**Comment by mkxml** [comment]
OK, the initial popup is implemented. We may improve that in the future, for now I'm closing this. 0.3.0 will be available later today and you can check the new features. Thank you @felipekm!

**Comment by felipekm** [comment]
Great! Cousin :+1:
