### ISSUE TITLE
One Light Theme

### ISSUE THREAD

**Issue by Ituury** [mkxml/atom-filesize#21]
Do you have any plans to add support for the One Light Theme ?

**Comment by mkxml** [comment]
I wasn't aware of any problems with the One Light Theme, I will check this out.

**Comment by mkxml** [comment]
I couldn't find any problems right away.

So I need to investigate your specific case.

What Atom version are you using? What OS? Are you using the last version of the package?

The screenshot below is on my machine using One Light Theme.

Your popup looks different in style from the screenshot below?

![one_light_screenshot](https://cloud.githubusercontent.com/assets/1051644/26399391/25667fb4-4053-11e7-9a58-8d7d56bd79a8.jpg)

**Comment by Ituury** [comment]
Well i think i have expressed myself incomprehensibly. So what i mean for the Light Theme is a specific style box as for the Solarized theme.

**Comment by mkxml** [comment]
Are you using the One Light UI theme with Solarized Light syntax theme?

What's your combination of UI theme and syntax theme?

Can you post your config?

**Comment by Ituury** [comment]
Default settings only UI Theme One Light and Syntax Theme One Light are set.

**Comment by mkxml** [comment]
Can you post a screenshot of the problem?

**Comment by Ituury** [comment]
I think it doesn't fit with the light theme. Maybe an more light box. Like the Solarized theme.

![screenshot from 2017-05-26 08-36-25](https://cloud.githubusercontent.com/assets/28138220/26483664/8015568c-41ee-11e7-8ab7-686cbbf0fcc0.png)

**Comment by mkxml** [comment]
Oh, now I get it. The package is picking the colors from the theme palette. Look at the other popups color, they follow the same pattern.

This theme had a lighter color for the popups in the past, looks like the Atom team changed them. They are now equal in One Dark and One Light themes.

The package always follows the style of the theme, so nothing I can do in this case.

**Comment by Ituury** [comment]
Alright but anyway thank you !
